services:
  - type: web
    name: ipfspp-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server3:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health

  - type: web
    name: ipfspp-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_ENV
        value: production
